name: pygom
channels:
  - conda-forge
dependencies:
  - python==3.13.13
  - jupyter
  - tqdm
  - dask
  - matplotlib
  - numpy
  - pandas
  - scipy
  - sympy
  - graphviz
  - cython
  - pip
  - pip:
    - -r requirements.txt
